server:
  port: 8080

# spring configuration using auto configured in memory db
spring:
  # override the default data source configuration
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: true
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: false
  h2.console.enabled: true # the JDBC URL is jdbc:h2:mem:testdb