server:
  port: 8081

spring.thymeleaf.template-loader-path: classpath:/templates
spring.thymeleaf.suffix: .html
spring.thymeleaf.cache: false
spring.h2.console.enabled: true
spring.h2.console.path: /h2-console